### ISSUE TITLE
Error connecting. Connection Timeout

### ISSUE THREAD

**Issue by kennetham** [cloudfoundry-community/bare-metal-bosh-lite#1]
Hi I tried running the example by Stark&Wayne
`STATIC_IP=x.x.x.x`
`knife solo prepare root@$STATIC_IP`

_My result_

``` text
WARNING: No knife configuration file found
Bootstrapping Chef...
root@x.x.x.x's password:
root@x.x.x.x's password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:02 --:--:--     0curl: (7)
Failed to connect to www.opscode.com port 443: Connection timeout

bash: install.sh: The file or directory could not be found
Generating node config 'nodes/x.x.x.x.json'...
```

In line with this, could anyone please advise, is there anything I would need to configure or setup to get this to work?

Please advise what I am missing?

**Comment by rkoster** [comment]
Bosh-lite has been refactored and I doubt this repo still works. For example they have switch from chef to [bosh-provisioner](https://github.com/cppforlife/bosh-provisioner). I have heard people had succes by using [vagrant-bosh](https://github.com/cppforlife/vagrant-bosh) in combination with [vagrant-managed-servers](https://github.com/tknerr/vagrant-managed-servers). The relevant manifest for vagrant-bosh can be found [here](https://github.com/cloudfoundry/bosh-lite/blob/master/templates/bosh_lite_manifest_template.yml)

**Comment by kennetham** [comment]
@rkoster thank you Ruben. I guess that's about all I could do for now. Appreciated the update.
